CREATE TABLE SECURITY_TYPE
(  ID INT NOT NULL,
   NAME VARCHAR(10),
   PRIMARY KEY (ID)
);

CREATE TABLE SECURITY
( ID INT NOT NULL,
  NAME VARCHAR(100),
  TICKER VARCHAR(10),
  SECURITY_TYPE INT NOT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT FK_SECURITY_TYPE FOREIGN KEY (ID)    REFERENCES SECURITY_TYPE(ID)
);